class AppStrings:
    appName = "CPU Scheduling Algorithms"
    arrivalTime = "Arrival time"
    burstTime = "Burst time"
    add = "Add"
    startCalc = "Start calculation"
    allProcessesView = "All processes view"
    selectTheOperation = "Select the operation"
    avWtMessage = "Average Waiting Time (AVWT)"
    avTatMessage = "Average Turn Around Time (AVTAT)"
